### ISSUE TITLE
[Docs] Waiting for the upload to complete

### ISSUE THREAD

**Issue by Aymkdn** [abramenal/cypress-file-upload#149]
### Current behavior:

There is no documentation on how to deal with the upload completion. You mentionned to use https://docs.cypress.io/api/commands/wait.html#Wait-for-a-specific-XHR-to-respond in a couple of issues (like https://github.com/abramenal/cypress-file-upload/issues/97 and https://github.com/abramenal/cypress-file-upload/issues/91), but I still don't get it…

### Desired behavior:

Could we have an example, in the documentation maybe? My use case is similar to the others: once the file is uploaded some stuff should appear in the page, and I should be able to test the page content.

Thank you

**Comment by Aymkdn** [comment]
In my scenario, I have a POST that is done at the end of the upload, to an URL that contains `moveTo`, so here is what I did:
```javascript
// check the POST requests
cy.server({method:"POST"});
// and in particular the one with "moveTo" in the URL
cy.route({
  method:'POST',
  url:/moveTo/
}).as('upload');

// start upload
let fileName = "upload_1.xlsx";
cy.fixture(fileName, 'binary')
    .then(Cypress.Blob.binaryStringToBlob)
    .then(fileContent => {
      cy.get('#input_upload_file').upload({ fileContent, fileName, mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', encoding:'utf8' })
})
// wait for the "moveTo" request, and leave a 2 minutes delay before throwing an error
cy.wait("@upload", {requestTimeout:120000});

// stop watching requests
cy.server({ enable: false })

// keep testing the app
// e.g. cy.get('.link_file[aria-label="upload_1"]').contains('(xlsx)');
```

I don't know if it's the best way, but at least I hope it will help others :-)

**Comment by abramenal** [comment]
Hi @Aymkdn 
Thanks for submitting the issue!

Your code snippet implements the idea I was suggesting perfectly. Thanks for the effort!
That is definitely a good idea to document that in a recipe as long as for many Cypress newcomers it might be tricky (especially since file upload isn't officially supported).

I've put this to the upcoming release backlog in order to make this. Keeping this issue open until code changes are made. If you feel you could help with that – I am happy to provide all necessary help for the contribution.

Cheers!

**Comment by abramenal** [comment]
@all-contributors add @Aymkdn for question
