### ISSUE TITLE
how to open an image file (help wanted)

### ISSUE THREAD

**Issue by km333** [abramenal/cypress-file-upload#15]
Hello any help appreciated. 
I think I have a very simple situation and I must be missing something.

I've installed the npm pkg and added the import to commands.js, and copied my file to fixtures

My html (Vue) is:
```
<input type="file"
           name="image"
           accept="image/*"
           @change="setImage"
      >
```

My Cypress test is:

```
  it('Uploads a jpg file', () => {
    cy.visit('uploadphoto')
    cy.fixture('myfile.jpg', 'base64').then(content => {
      cy.get('input').upload(content, 'myfile.jpg', 'image/jpeg')
    })
})
```

However when I run it the input is not populated with the file, and the @change event is not triggered either. This is a Vue project by the way.

Any help appreciated.

Cheers

**Comment by km333** [comment]
Update: For now I am using this solution instead from
https://github.com/cypress-io/cypress/issues/170 which is working for me

```
  it('Uploads a file', () => {
    cy.visit('uploadphoto')
    // from https://github.com/cypress-io/cypress/issues/170
    cy.fixture('david1.jpg', 'base64').then(img => {
      const base64image = img
      cy.get('[data-cy=file-input]').then(subject => {
        const type = 'image/jpeg'
        Cypress.Blob.base64StringToBlob(base64image, type).then(blob => {
          const testfile = new File([blob], 'david1.jpg', { type: type })
          const dataTransfer = new DataTransfer()
          dataTransfer.items.add(testfile)
          const input = subject[0]
          input.files = dataTransfer.files
        })
      })
    })
  })
```

**Comment by abramenal** [comment]
Hi @km333
Thanks for contribution!

It seems that originally I was thinking more on drag-n-drop inputs, thus it works via "drop" event.
https://github.com/abramenal/cypress-file-upload/blob/master/index.js#L9

Your case is a bit more simple and straightforward so I think it is definitely good to support that.
 How I see that is we need to explicitly point out which case to use - drag-n-grop or simple upload.

Are you in position of creating a pull request for that?
Otherwise I will publish the new version with this enhancement next week.
