### ISSUE TITLE
Engine Dependency needs to be updated

### ISSUE THREAD

**Issue by benwurth** [abramenal/cypress-file-upload#25]
### Current behavior:

When installing with yarn I received this error 
```
error cypress-file-upload@3.0.2: The engine "node" is incompatible with this module. Expected version ">8". Got "8.15.1"
```

### Desired behavior:

I would like to be able to install this fine module on a machine running nodejs 8.x.x

I expect this can be fixed (and still retain the desired behavior) by changing the dependency requirement to `>=8`.

### Steps to reproduce: (app code and test code)

1. Install nodejs 8.15.1 (I expect it to be reproducible with any version of node 8). 
2. Initialize an npm package.json in a new directory and add cypress-file-upload@3.0.2 to the dependencies. 
3. Finally, run `yarn`.

### Versions

- NodeJS: 8.15.1
- cypress-file-upload: 3.0.2
- OS: Ubuntu 18.04
- yarn: 1.13.0

**Comment by abramenal** [comment]
Hi @benwurth 
Thanks for submitting the issue!

This definitely should be fixed with `>=8` node engine version. I would be grateful if you can make a PR with this tiny change so we can place you in our honored contributors list.
If you're not able to make that – that's totally ok, I will do that later today.
