### ISSUE TITLE
not working with electron headless 

### ISSUE THREAD

**Issue by syedfaizanalef** [abramenal/cypress-file-upload#6]
When I do cypress run it does not trigger drop event, using react-dropzone.

**Comment by abramenal** [comment]
Hi @syedfaizanalef 
I have added an example app and it uses `react-dropzone` so that you can see how it is supposed to work.

https://github.com/abramenal/cypress-file-upload/tree/master/example

If that does not work for you, please feel free to open an issue with more detailed explanation. This should follow bug template and describe your setup, the issue you see with logs/screenshots/etc.

Cheers!
